### ISSUE TITLE
deform2 branch: bootstrap 3 rendering vs deform_bootstrap

### ISSUE THREAD

**Issue by gavinjackson** [Pylons/deform#247]
Hi guys,

Firstly thanks for writing such a great form handling library. I absolutely love it!
I'm busy porting my web applications from deform 0.9.9 (and deform_bootstrap) to deform2.0a2.
Just noticing a few UI inconsistencies, I was wondering if they were on the roadmap to be addressed?

http://deform2demo.repoze.org/mapping/
http://deformdemo.xo7.de/mapping/

Big fan of the tab UI, is there any way of switching it back on?

Also, I've noticed that the text field input boxes are huge, is there a way to resize these to match the max character size?

http://deformdemo.xo7.de/fielddefaults/
http://deform2demo.repoze.org/fielddefaults/

Again, thanks again for your great work!

**Comment by goodwillcoding** [comment]
deform2 now supports bootstrap3

**Comment by tisdall** [comment]
@goodwillcoding - Does bootstrap3 mean no tab UI?  Maybe you should explain that...

**Comment by stevepiercy** [comment]
This issue is a duplicate.

See https://github.com/Pylons/deform/issues/288 for the tab UI.

As far as text input widths, that's controlled now by wrapping the input with a div http://getbootstrap.com/css/#forms-control-sizes and has history in the issue tracker in https://github.com/Pylons/deform/pull/282 and https://github.com/Pylons/deform/pull/187

If that's not correct, please let me know where it is in error, and I'll consider reopening the issue.
