### ISSUE TITLE
Split bootstrap into a separate project

### ISSUE THREAD

**Issue by Themanwithoutaplan** [Pylons/deform#278]
Browsers have improved significantly since Deform was started. This is generally a good things as some of things that were more difficult back then have become more straightforward. But there has also been a proliferation of client-side frameworks such as Bootstrap and Angular.

Would it be an idea to split deform into a core system and have different packages for integrating with the various frameworks, similar to the way the various templating systems are used with Pyramid (pyramid_chameleon, pyramid_mako, etc.). A less monolithic approach would let those packages be updating in sync with the relevant frameworks, with Deform itself presumably receiving less frequent updates. 

Eg.
- deform-core
- deform-bootstrap
- deform-angular
- deform-jqueryui
  etc.

Is this feasible?
Assuming it is, what would be the minimal client-side requirement for Deform-core be? Does it still make sense to include external libraries at all? Or would it be sufficient to check for them and alert if they're missing? I'm thinking primarily of JQuery and Modernizr. If these are required then Deform will need to shadow security updates at least.

**Comment by tisdall** [comment]
The way things are are kind of "batteries included"...  It's essentially a "deform-core" mixed with "deform-bootstrap".  If you don't like the "deform-bootstrap" that comes with the package it's easy enough to override the templates and use something completely different (mostly).

There could probably be some improvements, though...  For example, most of the widgets have their JS and CSS requirements built into the code instead of being in the template (or somehow otherwise separate from the class).  This means you'd have to have separate "Angular" versions of widgets even though the rest of the code would likely remain the same.

I think the idea of making it easier to choose between popular frameworks has some merit, but someone would likely need to put in quite a bit of work.  And even if that work is done, it'll be difficult to find anyone to review it and merge it in.

**Comment by Themanwithoutaplan** [comment]
Yes, that's sort of what I'm thinking. Deform-core provides the infrastructure to work with the unholy mess of HTML forms. While the HTTP stuff isn't likely to change, HTML5 (and Houdini) at least gives us some hooks (sensible type, required and placeholder attributes) for a slightly richer base that the various client-side libraries can play with.

Widgets packs would work with this and hopefully concentrate on the templates.

**Comment by miohtama** [comment]
Closing this issue until there is Deform 3.0 under way.
